/**
 * web3.js
 *
 * Blockchain layer — handles all interaction with the Calculator smart contract
 * deployed on the Sepolia testnet.
 *
 * Responsibilities:
 *   - Connecting to MetaMask via the injected window.ethereum provider.
 *   - Verifying the user is on the correct network (Sepolia).
 *   - Encoding and sending transactions to the two contract entry points:
 *       · Calculate(num1, num2, op)
 *       · CalculateWithPriority(nums[], ops[])
 *   - Parsing emitted Solidity events from transaction receipts.
 *   - Watching for wallet / network changes.
 *
 * Dependencies:
 *   - ethers.js v6 loaded as a UMD bundle via CDN in index.html.
 *     The global `ethers` object is available on window — no ES module import
 *     is used here to avoid a bundler requirement.
 *   - config.js for CONTRACT_ADDRESS and NETWORK_ID.
 */

import { CONFIG } from './config.js';

// ─── Contract ABI ─────────────────────────────────────────────────────────────
// The ABI (Application Binary Interface) describes every function and event
// in Calculator.sol. ethers.js uses it to encode outgoing call data and decode
// incoming event logs. Generated by the Solidity compiler (Remix → ABI button).

const ABI = [
  // ── Events ──
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'int256', name: 'num1',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'num2',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'result', type: 'int256' },
    ],
    name: 'Addition_event',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'int256', name: 'num1',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'num2',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'result', type: 'int256' },
    ],
    name: 'Division_event',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'int256', name: 'result', type: 'int256' },
    ],
    name: 'Expression_event',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'int256', name: 'num1',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'num2',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'result', type: 'int256' },
    ],
    name: 'Multiplier_event',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'int256', name: 'num1',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'num2',   type: 'int256' },
      { indexed: false, internalType: 'int256', name: 'result', type: 'int256' },
    ],
    name: 'Subtraction_event',
    type: 'event',
  },
  // ── Functions ──
  {
    inputs: [
      { internalType: 'int256', name: 'num1_', type: 'int256' },
      { internalType: 'int256', name: 'num2_', type: 'int256' },
      { internalType: 'enum Calculator.Operator',  name: 'op_',   type: 'uint8'  },
    ],
    name: 'Calculate',
    outputs: [{ internalType: 'int256', name: 'Result_', type: 'int256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'int256[]', name: 'nums_', type: 'int256[]' },
      { internalType: 'enum Calculator.Operator[]', name: 'ops_',  type: 'uint8[]'  },
    ],
    name: 'CalculateWithPriority',
    outputs: [{ internalType: 'int256', name: 'Result_', type: 'int256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

// ─── Operator enum mapping ────────────────────────────────────────────────────
// Maps operator names (used internally in JS) to the uint8 values expected by
// the Solidity enum: enum Operator { Addition, Subtraction, Multiplier, Division }
const OP_INDEX = {
  Addition:    0,
  Subtraction: 1,
  Multiplier:  2,
  Division:    3,
};

// ─── Connection state ─────────────────────────────────────────────────────────
// Module-level singletons. Initialised by initWeb3() and reused for every
// subsequent contract call within the same session.
let provider = null; // ethers.BrowserProvider wrapping window.ethereum
let signer   = null; // the connected wallet account (signs transactions)
let contract = null; // ethers.Contract instance bound to the deployed address

// ─── initWeb3 ─────────────────────────────────────────────────────────────────

/**
 * Connects the user's MetaMask wallet and initialises the contract instance.
 *
 * Steps:
 *   1. Verify window.ethereum (MetaMask) is present.
 *   2. Request account access — triggers the MetaMask popup.
 *   3. Wrap the provider with ethers.BrowserProvider.
 *   4. Verify the wallet is on Sepolia (chainId 11155111).
 *      Chain IDs are compared as strings because ethers v6 returns BigInt
 *      and CONFIG.NETWORK_ID is a plain Number — strict equality would always
 *      fail across those two types.
 *   5. Instantiate ethers.Contract with the ABI and signer.
 *
 * @returns {Promise<string>} The connected wallet address (checksummed).
 * @throws  {Error} If MetaMask is absent, the user rejects access, or the
 *                  wallet is on the wrong network.
 */
export async function initWeb3() {
  if (!window.ethereum) {
    throw new Error('MetaMask not detected. Please install the MetaMask extension.');
  }

  // Prompt the user to grant account access.
  await window.ethereum.request({ method: 'eth_requestAccounts' });

  provider = new ethers.BrowserProvider(window.ethereum);
  signer   = await provider.getSigner();

  // Network guard — compare as strings to handle BigInt vs Number safely.
  const network = await provider.getNetwork();
  if (network.chainId.toString() !== CONFIG.NETWORK_ID.toString()) {
    throw new Error(
      `Please switch to Sepolia Testnet (Chain ID: 11155111). ` +
      `Your wallet is currently on Chain ID: ${network.chainId}.`
    );
  }

  contract = new ethers.Contract(CONFIG.CONTRACT_ADDRESS, ABI, signer);

  return await signer.getAddress();
}

/** Returns true if the wallet has been connected and the contract initialised. */
export function isConnected() {
  return contract !== null;
}

/** Returns the currently connected wallet address, or null if not connected. */
export async function getAccount() {
  if (!signer) return null;
  return await signer.getAddress();
}

// ─── callCalculate ────────────────────────────────────────────────────────────

/**
 * Calls Calculate(num1, num2, op) on the deployed contract.
 * Used for simple two-operand expressions (e.g. 5 + 3).
 *
 * Numbers are truncated to integers before being converted to BigInt because
 * Solidity's int256 does not support decimals — fractional parts would be
 * silently discarded on-chain anyway.
 *
 * @param  {number} num1 - First operand.
 * @param  {number} num2 - Second operand.
 * @param  {string} op   - Operator name ('Addition' | 'Subtraction' | 'Multiplier' | 'Division').
 * @returns {Promise<{ result: number, txHash: string, blockNumber: number, events: Array }>}
 */
export async function callCalculate(num1, num2, op) {
  if (!isConnected()) throw new Error('Wallet not connected.');

  const opEnum = OP_INDEX[op];
  const n1     = BigInt(Math.trunc(num1));
  const n2     = BigInt(Math.trunc(num2));

  // Send the transaction and wait for it to be mined.
  const tx      = await contract.Calculate(n1, n2, opEnum);
  const receipt = await tx.wait();

  const events = _parseEvents(receipt);
  // The result is in the last argument of the operation event
  // (Addition_event, Subtraction_event, etc.).
  const result = _extractResult(events, [
    'Addition_event', 'Subtraction_event', 'Multiplier_event', 'Division_event',
  ]);

  return {
    result:      result !== null ? Number(result) : null,
    txHash:      receipt.hash,
    blockNumber: receipt.blockNumber,
    events,
  };
}

// ─── callCalculateWithPriority ────────────────────────────────────────────────

/**
 * Calls CalculateWithPriority(nums[], ops[]) on the deployed contract.
 * Used for expressions with three or more operands (e.g. 2 + 3 × 4).
 * Mathematical precedence (× ÷ before + −) is enforced on-chain.
 *
 * @param  {number[]} nums - Array of operands (minimum 2).
 * @param  {string[]} ops  - Array of operator names (length = nums.length - 1).
 * @returns {Promise<{ result: number, txHash: string, blockNumber: number, events: Array }>}
 */
export async function callCalculateWithPriority(nums, ops) {
  if (!isConnected()) throw new Error('Wallet not connected.');

  const numsBI  = nums.map(n => BigInt(Math.trunc(n)));
  const opsEnum = ops.map(op => OP_INDEX[op]);

  const tx      = await contract.CalculateWithPriority(numsBI, opsEnum);
  const receipt = await tx.wait();

  const events = _parseEvents(receipt);
  // The final result is carried by Expression_event, emitted at the end
  // of CalculateWithPriority after all sub-operations have resolved.
  const result = _extractResult(events, ['Expression_event']);

  return {
    result:      result !== null ? Number(result) : null,
    txHash:      receipt.hash,
    blockNumber: receipt.blockNumber,
    events,
  };
}

// ─── watchNetworkChanges ──────────────────────────────────────────────────────

/**
 * Registers listeners on the MetaMask provider for network and account changes.
 * Both events invalidate the current session — the callback should prompt the
 * user to reconnect.
 *
 * @param {Function} callback - Called with no arguments when either event fires.
 */
export function watchNetworkChanges(callback) {
  if (!window.ethereum) return;
  window.ethereum.on('chainChanged',    () => callback?.());
  window.ethereum.on('accountsChanged', () => callback?.());
}

// ─── Private helpers ──────────────────────────────────────────────────────────

/**
 * Parses all logs in a transaction receipt into a normalised array of events.
 * Logs that cannot be decoded by the contract interface (e.g. logs from other
 * contracts) are silently filtered out.
 *
 * @param  {TransactionReceipt} receipt
 * @returns {{ name: string, args: string[] }[]}
 */
function _parseEvents(receipt) {
  return receipt.logs
    .map(log => {
      try { return contract.interface.parseLog(log); }
      catch { return null; }
    })
    .filter(Boolean)
    .map(e => ({
      name: e.name,
      args: e.args.map(a => a.toString()), // convert BigInt args to plain strings
    }));
}

/**
 * Finds the first event whose name is in `names` and returns its last argument,
 * which by convention holds the operation result in all Calculator events.
 *
 * @param  {{ name: string, args: string[] }[]} events
 * @param  {string[]} names - Event names to search for.
 * @returns {string | null} The result as a string, or null if not found.
 */
function _extractResult(events, names) {
  for (const ev of events) {
    if (names.includes(ev.name)) {
      return ev.args[ev.args.length - 1];
    }
  }
  return null;
}
